# Generated by Django 5.1.1 on 2024-09-27 18:21

import bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(choices=bot.models.get_roles, max_length=16)),
                ("content", models.CharField(max_length=1024)),
                ("temperature", models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
