# Generated by Django 5.1.1 on 2024-10-08 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_remove_chatsession_qa_alter_message_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="session",
            field=models.ForeignKey(
                default=[],
                on_delete=django.db.models.deletion.CASCADE,
                to="bot.chatsession",
            ),
        ),
    ]
