# Generated by Django 5.1.2 on 2024-10-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0006_alter_chatsession_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "user"),
                    ("system", "system"),
                    ("assistant", "assistant"),
                ],
                max_length=16,
            ),
        ),
    ]
