# Generated by Django 5.1.2 on 2024-11-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0007_alter_message_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="topic",
            field=models.CharField(default="New chat", max_length=255),
        ),
    ]
